package academy;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;


public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginForm.class.getName());

    public Login() {
        initComponents();
        
        this.setTitle("Login");
     
        // no no max button cuz it has bad GUI xD
    setResizable(false);

    // run file go center of screen xD
    setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        tgbtnShowpassword = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnSignup = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo2.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        tgbtnShowpassword.setBackground(new java.awt.Color(232, 197, 106));
        tgbtnShowpassword.setFont(new java.awt.Font("TimesNewPixel", 0, 14)); // NOI18N
        tgbtnShowpassword.setForeground(new java.awt.Color(0, 0, 0));
        tgbtnShowpassword.setText("show password");
        tgbtnShowpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbtnShowpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(tgbtnShowpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, -1, -1));

        jLabel3.setFont(new java.awt.Font("Pixel Georgia", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 102));
        jLabel3.setText("don't have an account?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, -1, -1));

        jLabel2.setFont(new java.awt.Font("Pixel Georgia", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 102));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        jLabel4.setFont(new java.awt.Font("Pixel Georgia", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 102));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        btnExit.setBackground(new java.awt.Color(232, 197, 106));
        btnExit.setFont(new java.awt.Font("OldWizard", 1, 36)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setText("Exit");
        btnExit.setBorder(new javax.swing.border.MatteBorder(null));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 752, 80, 50));

        btnSignup.setBackground(new java.awt.Color(232, 197, 106));
        btnSignup.setFont(new java.awt.Font("OldWizard", 1, 36)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(0, 0, 0));
        btnSignup.setText("Sign up");
        btnSignup.setBorder(new javax.swing.border.MatteBorder(null));
        btnSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 652, 140, 50));

        btnLogin.setBackground(new java.awt.Color(232, 197, 106));
        btnLogin.setFont(new java.awt.Font("OldWizard", 1, 36)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Login");
        btnLogin.setBorder(new javax.swing.border.MatteBorder(null));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 650, 110, 50));

        txtPassword.setBackground(new java.awt.Color(167, 138, 106));
        txtPassword.setFont(new java.awt.Font("Pixel Georgia", 0, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(232, 197, 106));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 460, 50));

        txtUsername.setBackground(new java.awt.Color(167, 138, 106));
        txtUsername.setFont(new java.awt.Font("Pixel Georgia", 0, 24)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(232, 197, 106));
        txtUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUsername.setDisabledTextColor(new java.awt.Color(153, 153, 0));
        txtUsername.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 460, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bookclose1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
        JFrame animationFrame = new JFrame();
animationFrame.setUndecorated(true); // removes borders
animationFrame.setSize(1000, 800);
animationFrame.setLocationRelativeTo(this);

JLabel gifLabel = new JLabel(new ImageIcon(getClass().getResource("/Images/geunyeong-park-book.gif")));
animationFrame.setContentPane(gifLabel);

// Show the animation window
animationFrame.setVisible(true);

Timer timer = new javax.swing.Timer(2000, e -> {
    animationFrame.dispose();           // close the animation window
    new Signup().setVisible(true);      // open your registration frame
     this.dispose(); // 'this' = Login frame
});
timer.setRepeats(false);                // <- fire only once
timer.start();

        
    }//GEN-LAST:event_btnSignupActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText().trim();
String password = txtPassword.getText().trim();

if (UserData.validateUser(username, password)) {
    JOptionPane.showMessageDialog(this, "Login successful!");
    this.dispose();
    new Menu().setVisible(true);
    
} else {
    JOptionPane.showMessageDialog(this, "Invalid username or password!");
}

        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0); // exits the entire program
    }//GEN-LAST:event_btnExitActionPerformed

    private void tgbtnShowpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbtnShowpasswordActionPerformed
        // TODO add your handling code here:
        //para ma kita ang password with a toggle button crzyyyy
        tgbtnShowpassword.addActionListener(e -> {
    if (tgbtnShowpassword.isSelected()) {
        txtPassword.setEchoChar((char)0); // show password
    } else {
        txtPassword.setEchoChar('•');    // hide password, use whatever char you want
    }
});
    }//GEN-LAST:event_tgbtnShowpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JToggleButton tgbtnShowpassword;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
